/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import modelo.conexion;


/**
 *
 * @author rodri
 */
public class frmregistro extends javax.swing.JDialog {
    
conexion cn = new conexion();
Connection con = cn.conectar();

 
    
    public frmregistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtrnombreusuario = new javax.swing.JTextField();
        txtrapellido = new javax.swing.JTextField();
        txtrcorreo = new javax.swing.JTextField();
        txtrnombre = new javax.swing.JTextField();
        txtrtelefono = new javax.swing.JTextField();
        txtrcontrasena = new javax.swing.JPasswordField();
        txtrconfirmacontrasena = new javax.swing.JPasswordField();
        txtrconfirmaregistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(12, 13, 7));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Usuario"));

        txtrnombreusuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre de usuario"));

        txtrapellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));

        txtrcorreo.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));

        txtrnombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtrtelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero de telefono"));
        txtrtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrtelefonoActionPerformed(evt);
            }
        });

        txtrcontrasena.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));

        txtrconfirmacontrasena.setBorder(javax.swing.BorderFactory.createTitledBorder("Confirma Contraseña"));
        txtrconfirmacontrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrconfirmacontrasenaActionPerformed(evt);
            }
        });

        txtrconfirmaregistro.setBackground(new java.awt.Color(254, 182, 2));
        txtrconfirmaregistro.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtrconfirmaregistro.setForeground(new java.awt.Color(0, 0, 0));
        txtrconfirmaregistro.setText("Registrar");
        txtrconfirmaregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrconfirmaregistroActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\OneDrive\\Escritorio\\Iconos\\registrarse.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtrcontrasena)
                            .addComponent(txtrtelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(txtrnombre)
                            .addComponent(txtrcorreo)
                            .addComponent(txtrapellido)
                            .addComponent(txtrnombreusuario)
                            .addComponent(txtrconfirmacontrasena)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(txtrconfirmaregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtrnombreusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtrnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtrapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtrtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtrcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtrcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtrconfirmacontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtrconfirmaregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrconfirmacontrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrconfirmacontrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrconfirmacontrasenaActionPerformed

    private void txtrtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrtelefonoActionPerformed

    private void txtrconfirmaregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrconfirmaregistroActionPerformed
        // TODO add your handling code here:
               String nombreusuario = txtrnombreusuario.getText();
        String nombre = txtrnombre.getText();
        String apellido = txtrapellido.getText();
        String telefono = txtrtelefono.getText();
        String correo = txtrcorreo.getText();
        String contrasena = new String(txtrcontrasena.getPassword());
        String confirmacontrasena = new String(txtrconfirmacontrasena.getPassword());

        if (nombreusuario.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() || correo.isEmpty() || contrasena.isEmpty() || confirmacontrasena.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe rellenar todos los campos");
        } else {
            // Validar formato del correo
            if (!correo.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese un correo electrónico válido");
            } else {
                // Validar si las contraseñas coinciden
                if (!contrasena.equals(confirmacontrasena)) {
                    JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
                } else {
                    if (con == null) {
                        JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos");
                        return;  // Salir del método si no hay conexión
                    }

                    try {
                        String consulta = "INSERT INTO usuarios(UserName, Nombre, Apellido, Telefono, Email, Password) VALUES (?, ?, ?, ?, ?, ?)";
                        PreparedStatement ps = con.prepareStatement(consulta);
                        ps.setString(1, nombreusuario);
                        ps.setString(2, nombre);
                        ps.setString(3, apellido);
                        ps.setString(4, telefono);
                        ps.setString(5, correo);
                        ps.setString(6, contrasena);
                        ps.executeUpdate();
                        limpiar();
                        JOptionPane.showMessageDialog(null, "Datos registrados con éxito");
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Error al registrar los datos: " + e.getMessage());
                    } finally {
                        try {
                            if (con != null) con.close();  // Cerrar la conexión
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage());
                        }
                    }
                }
            }
        }

    

        
    }//GEN-LAST:event_txtrconfirmaregistroActionPerformed

    void limpiar(){
        
        txtrnombreusuario.setText("");
        txtrnombre.setText("");
        txtrapellido.setText("");
        txtrtelefono.setText("");
        txtrcorreo.setText("");
        txtrcontrasena.setText("");
        txtrconfirmacontrasena.setText("");
        
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmregistro dialog = new frmregistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtrapellido;
    private javax.swing.JPasswordField txtrconfirmacontrasena;
    private javax.swing.JButton txtrconfirmaregistro;
    private javax.swing.JPasswordField txtrcontrasena;
    private javax.swing.JTextField txtrcorreo;
    private javax.swing.JTextField txtrnombre;
    private javax.swing.JTextField txtrnombreusuario;
    private javax.swing.JTextField txtrtelefono;
    // End of variables declaration//GEN-END:variables
}
