/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.frproductos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Productos;

/**
 *
 * @author Francisco Rodriguez
 */
public class menuproductos extends javax.swing.JPanel {
    Productos pr=new Productos();
    frproductos frp=new frproductos();
    DefaultTableModel modeloProductos=new DefaultTableModel();


    public menuproductos() {
        initComponents();
        listarProductos();
        
    }
    
    private void listarProductos(){
        List<Productos> lista= frp.Listar();
        modeloProductos= (DefaultTableModel) tblproductos.getModel();
        Object[] ob=new Object[6];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdProducto();
            ob[1]=lista.get(i).getNombreProducto();
            ob[2]=lista.get(i).getMarcaProducto();
            ob[3]=lista.get(i).getCategoriaProducto();
            ob[4]=lista.get(i).getPrecioProducto();
            ob[5]=lista.get(i).getStockProducto();
            modeloProductos.addRow(ob);
        }
        tblproductos.setModel(modeloProductos);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jdatos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtpcategoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        txtpnombre = new javax.swing.JTextField();
        txtpmarca = new javax.swing.JTextField();
        txtpprecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtpstock = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        joperaciones = new javax.swing.JPanel();
        btneproductos = new javax.swing.JButton();
        btneditproducto = new javax.swing.JButton();
        btnrproductos = new javax.swing.JButton();
        jbasedatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproductos = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de productos");

        jdatos.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Categoria");

        txtpcategoria.setBackground(new java.awt.Color(255, 255, 255));
        txtpcategoria.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stock");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        txtpid.setBackground(new java.awt.Color(255, 255, 255));
        txtpid.setForeground(new java.awt.Color(0, 0, 0));

        txtpnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtpnombre.setForeground(new java.awt.Color(0, 0, 0));

        txtpmarca.setBackground(new java.awt.Color(255, 255, 255));
        txtpmarca.setForeground(new java.awt.Color(0, 0, 0));

        txtpprecio.setBackground(new java.awt.Color(255, 255, 255));
        txtpprecio.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marca");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio");

        txtpstock.setBackground(new java.awt.Color(255, 255, 255));
        txtpstock.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id");

        javax.swing.GroupLayout jdatosLayout = new javax.swing.GroupLayout(jdatos);
        jdatos.setLayout(jdatosLayout);
        jdatosLayout.setHorizontalGroup(
            jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdatosLayout.createSequentialGroup()
                        .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdatosLayout.createSequentialGroup()
                                .addComponent(txtpprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE))
                            .addGroup(jdatosLayout.createSequentialGroup()
                                .addComponent(txtpcategoria)
                                .addGap(108, 108, 108)))
                        .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpstock, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(jdatosLayout.createSequentialGroup()
                        .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdatosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtpmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jdatosLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtpnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jdatosLayout.setVerticalGroup(
            jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdatosLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdatosLayout.createSequentialGroup()
                        .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtpnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdatosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(jdatosLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdatosLayout.createSequentialGroup()
                        .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdatosLayout.createSequentialGroup()
                        .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtpstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdatosLayout.createSequentialGroup()
                        .addGroup(jdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap())))
        );

        joperaciones.setBackground(new java.awt.Color(0, 0, 0));

        btneproductos.setBackground(new java.awt.Color(254, 182, 2));
        btneproductos.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btneproductos.setForeground(new java.awt.Color(0, 0, 0));
        btneproductos.setText("Eliminar");
        btneproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneproductosActionPerformed(evt);
            }
        });

        btneditproducto.setBackground(new java.awt.Color(254, 182, 2));
        btneditproducto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btneditproducto.setForeground(new java.awt.Color(0, 0, 0));
        btneditproducto.setText("Actualizar");
        btneditproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditproductoActionPerformed(evt);
            }
        });

        btnrproductos.setBackground(new java.awt.Color(254, 182, 2));
        btnrproductos.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnrproductos.setForeground(new java.awt.Color(0, 0, 0));
        btnrproductos.setText("Registrar");
        btnrproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrproductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout joperacionesLayout = new javax.swing.GroupLayout(joperaciones);
        joperaciones.setLayout(joperacionesLayout);
        joperacionesLayout.setHorizontalGroup(
            joperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joperacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnrproductos)
                .addGap(55, 55, 55)
                .addComponent(btneditproducto)
                .addGap(48, 48, 48)
                .addComponent(btneproductos)
                .addGap(131, 131, 131))
        );
        joperacionesLayout.setVerticalGroup(
            joperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joperacionesLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(joperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrproductos)
                    .addComponent(btneditproducto)
                    .addComponent(btneproductos)))
        );

        jbasedatos.setBackground(new java.awt.Color(0, 0, 0));

        tblproductos.setBackground(new java.awt.Color(255, 255, 255));
        tblproductos.setForeground(new java.awt.Color(0, 0, 0));
        tblproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProducto", "NombreProducto", "MarcaProducto", "CategoriaProducto", "PrecioProducto", "StockProducto"
            }
        ));
        tblproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproductos);

        javax.swing.GroupLayout jbasedatosLayout = new javax.swing.GroupLayout(jbasedatos);
        jbasedatos.setLayout(jbasedatosLayout);
        jbasedatosLayout.setHorizontalGroup(
            jbasedatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbasedatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jbasedatosLayout.setVerticalGroup(
            jbasedatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbasedatosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbasedatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(258, 258, 258))
            .addComponent(joperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbasedatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnrproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrproductosActionPerformed

try {
        // Verificar si los campos no están vacíos antes de convertir
        if (txtpnombre.getText().isEmpty() || txtpmarca.getText().isEmpty() || 
            txtpcategoria.getText().isEmpty() || txtpprecio.getText().isEmpty() || 
            txtpstock.getText().isEmpty()) {
            throw new NumberFormatException("Uno o más campos están vacíos");//mostrar en pantalla el mensaje entre comillas
        }

        // Obtener y convertir los datos de los campos de texto
        String nombreProducto = txtpnombre.getText();
        String marcaProducto = txtpmarca.getText();
        String categoriaProducto = txtpcategoria.getText();
        int precioProducto = Integer.parseInt(txtpprecio.getText());
        int stockProducto = Integer.parseInt(txtpstock.getText());

        // Establecer los valores en el objeto Producto
        pr.setNombreProducto(nombreProducto);
        pr.setMarcaProducto(marcaProducto);
        pr.setCategoriaProducto(categoriaProducto);
        pr.setPrecioProducto(precioProducto);
        pr.setStockProducto(stockProducto);

        // Intentar registrar el producto
        if(frp.insertar(pr)){
            JOptionPane.showMessageDialog(null, "Producto registrado con éxito"); //mostrar en pantalla el mensaje entre comillas
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar el producto");//mostrar en pantalla el mensaje entre comillas
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese valores válidos para los campos numéricos");//mostrar en pantalla el mensaje entre comillas
    }
    limpiarTablaProductos();
    limpiarCampos();
    listarProductos();
  
    }//GEN-LAST:event_btnrproductosActionPerformed

    private void btneditproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditproductoActionPerformed
        // TODO add your handling code here:
        int fila = tblproductos.getSelectedRow();
        if(fila==-1){
           JOptionPane.showMessageDialog(null, "Seleccione un producto"); 
        }else{
            pr.setIdProducto(Integer.parseInt(txtpid.getText()));
            pr.setNombreProducto(txtpnombre.getText());
            pr.setMarcaProducto(txtpmarca.getText());
            pr.setCategoriaProducto(txtpcategoria.getText());
            pr.setPrecioProducto(Integer.parseInt(txtpprecio.getText()));
            pr.setStockProducto(Integer.parseInt(txtpstock.getText()));
            if(frp.editar(pr)){
                JOptionPane.showMessageDialog(null, "Modificacion exitosa");
            limpiarTablaProductos();
            limpiarCampos();
            listarProductos();
            }
        }
    }//GEN-LAST:event_btneditproductoActionPerformed

    private void tblproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductosMouseClicked
        // TODO add your handling code here:
        int fila=tblproductos.getSelectedRow();
        txtpid.setText(tblproductos.getValueAt(fila, 0).toString());
        txtpnombre.setText(tblproductos.getValueAt(fila, 1).toString());
        txtpmarca.setText(tblproductos.getValueAt(fila, 2).toString());
        txtpcategoria.setText(tblproductos.getValueAt(fila, 3).toString());
        txtpprecio.setText(tblproductos.getValueAt(fila, 4).toString());
        txtpstock.setText(tblproductos.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_tblproductosMouseClicked

    private void btneproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneproductosActionPerformed
        // TODO add your handling code here:
        if(!txtpid.getText().isEmpty()){
            int confirmacion=JOptionPane.showConfirmDialog(null, "¿Seguro que quieres eliminar este producto?","Confirmacion",2);//mostrar en pantalla el mensaje entre comillas, a parte el panel flotante que saldra se llamara confirmacion
            if(confirmacion==0){
                pr.setIdProducto(Integer.parseInt(txtpid.getText()));
                frp.eliminar(pr);
                limpiarTablaProductos();
                limpiarCampos();
                listarProductos();
                JOptionPane.showMessageDialog(null, "Producto eliminado correctamente");//mostrar en pantalla el mensaje entre comillas
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una categoria");//mostrar en pantalla el mensaje entre comillas
        }
    }//GEN-LAST:event_btneproductosActionPerformed


    void limpiarCampos(){ // metodo para limpiar los campos
        txtpnombre.setText("");
        txtpmarca.setText("");
        txtpcategoria.setText("");
        txtpprecio.setText("");
        txtpid.setText("");
        txtpstock.setText("");
    }
    
    void limpiarTablaProductos(){ // metodo para limpiar la tabla prodctos
        for(int i=0;1<modeloProductos.getRowCount();i++){
            modeloProductos.removeRow(i);
            i=0-1;
        }
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditproducto;
    private javax.swing.JButton btneproductos;
    private javax.swing.JButton btnrproductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jbasedatos;
    private javax.swing.JPanel jdatos;
    private javax.swing.JPanel joperaciones;
    private javax.swing.JTable tblproductos;
    private javax.swing.JTextField txtpcategoria;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtpmarca;
    private javax.swing.JTextField txtpnombre;
    private javax.swing.JTextField txtpprecio;
    private javax.swing.JTextField txtpstock;
    // End of variables declaration//GEN-END:variables
}
